version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: permissions.sh
      timeout: 300
      runas: root
      
      
